// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB33BDzzAuZtVXRAIbLuLUsjINUnQAwul8',
    appId: '1:319357934135:web:f298479e29dfdb4f17bdb2',
    messagingSenderId: '319357934135',
    projectId: 'personal-trainer-52788',
    authDomain: 'personal-trainer-52788.firebaseapp.com',
    storageBucket: 'personal-trainer-52788.firebasestorage.app',
    measurementId: 'G-XDKSEEXHQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdOezmJqjCBTPqH04FWs1-fw3kMsXtuP4',
    appId: '1:319357934135:android:3813b6a49900e82417bdb2',
    messagingSenderId: '319357934135',
    projectId: 'personal-trainer-52788',
    storageBucket: 'personal-trainer-52788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY0W17yl7DjOFGZAYOS2noW0-581zo5kY',
    appId: '1:319357934135:ios:43170afa98b263ac17bdb2',
    messagingSenderId: '319357934135',
    projectId: 'personal-trainer-52788',
    storageBucket: 'personal-trainer-52788.firebasestorage.app',
    iosBundleId: 'com.example.personaltrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY0W17yl7DjOFGZAYOS2noW0-581zo5kY',
    appId: '1:319357934135:ios:43170afa98b263ac17bdb2',
    messagingSenderId: '319357934135',
    projectId: 'personal-trainer-52788',
    storageBucket: 'personal-trainer-52788.firebasestorage.app',
    iosBundleId: 'com.example.personaltrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB33BDzzAuZtVXRAIbLuLUsjINUnQAwul8',
    appId: '1:319357934135:web:31bcf1acfc00027217bdb2',
    messagingSenderId: '319357934135',
    projectId: 'personal-trainer-52788',
    authDomain: 'personal-trainer-52788.firebaseapp.com',
    storageBucket: 'personal-trainer-52788.firebasestorage.app',
    measurementId: 'G-3LLNYTJR2X',
  );
}
